apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: mongodb
    labels:
        app: mongo
        tier: database
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo
            tier: database
    template:
        metadata:
            labels:
                app: mongo
                tier: database
        spec:
            containers:
                - name: mongodb
                  image: mongo:4
                  ports:
                    - containerPort: 27017
                  env:
                    - name: MONGO_INITDB_ROOT_USERNAME
                      value: admin
                    - name: MONGO_INITDB_ROOT_PASSWORD
                      value: password
                  args: ["--auth"]